### ISSUE TITLE
[ufo3] notifications timing problems

### ISSUE THREAD

**Issue by adrientetar** [typesupply/defcon#29]
So I was implementing a way to move a glyph to another layer. I call `glyph.clearContours()` after inserting the glyph into another layer.

The problem that I have is that I have representations of my glyph that are destroyed when `Glyph.Changed` is emitted, and I also update my view when `Glyph.Changed` emitted.

The thing is that apparently defcon calls my update callbacks before destroying the representations. It makes the application crash when it trys to access data that was removed:

```
RLS Layer.GlyphWillBeAdded <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphAdded <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04AEC430>
RLS Glyph.ContourWillBeDeleted <defconQt.objects.defcon.TGlyph object at 0x04C38CB0>
RLS Glyph.ContoursChanged <defconQt.objects.defcon.TGlyph object at 0x04C38CB0>
RLS Glyph.Changed <defconQt.objects.defcon.TGlyph object at 0x04C38CB0>
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 428, in _layerMove
    self.view.layerMove()
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 2385, in layerMove
    self._glyph.clearContours()
  File "C:\Python34\lib\site-packages\defcon\objects\glyph.py", line 523, in clearContours
    self.releaseHeldNotifications()
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 162, in releaseHeldNotifications
    dispatcher.releaseHeldNotifications(observable=self, notification=notification)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 251, in releaseHeldNotifications
    self.postNotification(notification, observableRef(), data)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 2010, in _glyphChanged
    self.activeGlyphChanged()
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 2032, in activeGlyphChanged
    self.updateActiveLayer()
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 2041, in updateActiveLayer
    self.addPoints()
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\glyphView.py", line 2318, in addPoints
    self._glyph[onCurve.contourIndex],
  File "C:\Python34\lib\site-packages\defcon\objects\glyph.py", line 1023, in __getitem__
    return self._contours[index]
IndexError: list index out of range
```

If I return early in my widgets instead of updating I can see the calls to destroy happening:

```
RLS Layer.GlyphWillBeAdded <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphAdded <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.GlyphChanged <defcon.objects.layer.Layer object at 0x04C46930>
RLS Layer.Changed <defcon.objects.layer.Layer object at 0x04C46930>
RLS Glyph.ContourWillBeDeleted <defconQt.objects.defcon.TGlyph object at 0x04E4EB30>
RLS Glyph.ContoursChanged <defconQt.objects.defcon.TGlyph object at 0x04E4EB30>
RLS Glyph.Changed <defconQt.objects.defcon.TGlyph object at 0x04E4EB30>
DESTROY defconQt.QPainterPath
DESTROY defconQt.OutlineInformation
DESTROY defconQt.StartPointsInformation
DESTROY defconQt.NoComponentsQPainterPath
```

I could set my representations to be destroyed when `ContourWillBeDeleted` is emitted (is it meant to be so? ufo3 defconAppkit does not seem to care about `ContourWillBeDeleted` specially, but it isn't capable of editing either) but I feel like there are other cases where such a thing could happen. 
@typesupply What do you think?

**Comment by adrientetar** [comment]
Okay, I figured that what I'm seeing shouldn't happen given that beginSelfNotificationObservation is called immediately after an object is instanciated. 
I might have a problem with how elements are ordered in the dict...

**Comment by adrientetar** [comment]
It doesn't seem to be an ordering issue...

**Comment by adrientetar** [comment]
Okay I think this happened because I wanted to transfer the glyph to another layer and putting a glyph in two distinct layers at once does bad things since layers observe their glyph. For future reference.
