### ISSUE TITLE
UFO3 info.getDataForSerialization()

### ISSUE THREAD

**Issue by typemytype** [typesupply/defcon#73]
```python
from defcon import Font
f = Font()

f.info.getDataForSerialization()
```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/frederik/Documents/dev/typesupply/defcon/Lib/defcon/objects/info.py", line 296, in getDataForSerialization
    getters.append((name, simple_get))
NameError: global name 'getters' is not defined
```

**Comment by adrientetar** [comment]
cc @graphicore

**Comment by typemytype** [comment]
fixed https://github.com/typesupply/defcon/commit/7c0f26b0443b2eb955045c05c865d82c22794c8d

**Comment by adrientetar** [comment]
Lgtm
